nia_search:
  evaluations: 100
  runs: 1
  algorithms:
    - particle_swarm
    - genetic_algorithm
    - firefly_algorithm
    - differential_evolution
    - self_adaptive_differential_evolution

data_params:
  dataset_type: "MSL"  # Can be "ECG5000", "YahooA1", "KPI", "MSL"
  data_path: "data/msl_dataset/" # Can be ecg5000_dataset, yahoo_dataset, kpi_dataset, "msl_dataset"
  seq_len: 200 # 140, 200
  n_features: 55 # MSL:55 Multiple features problem https://stackoverflow.com/questions/71565854/lstm-autoencoder-set-up-for-multiple-features-using-pytorch
  data_percentage: 5
  batch_size: 10
  train_size: 70
  val_size: 10
  test_size: 20
  num_workers: 0
  pin_memory: True

trainer_params:
  min_epochs: 2
  max_epochs: 2

early_stop:
  monitor: "val_loss"
  patience: 5
  min_delta: 0.00
  mode: "min"

fine_tune_lr_finder:
  tune_n_epochs: 5
  lr_finder:
    mode: "exponential" #"linear"
    num_training_steps: 100
    attr_name: "learning_rate"
    update_attr: True
    early_stop_threshold: # None # https://github.com/Lightning-AI/lightning/issues/4846#issuecomment-1014148839

model_params:
  name: 'RecurrentVariationalAutoencoder'

exp_params:
  weight_decay: 0.001
  kld_weight: 0.1
  manual_seed: 1265

logging_params:
  name: "RNNVAE"
  logger_file: "RNNAutoencoder.log"
  save_dir: "logs/"
  db_storage: "logs/solution.db"